[package]
name = "klownie_matrix"
version = "0.1.0"
edition = "2021"
authors = ["Audrick YEU <audrickyeu@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num = "0.4.0"
